### ISSUE TITLE
Brody UI improvements: reset, zoom buttons, rotation

### ISSUE THREAD

**Issue by shentonfreude** [koansys/isat#62]
3D View
- +/- buttons for zooming
- Axis reset for Earth rotation, brings rotation back to the default
- Auto rotation of the Earth on the proper axis, with play/pause button

2.5D & 2D View
- Limitations on dragging so left and right edges of Earth display won't come inside app window (ask questions if I didn't explain this clearly enough)

**Comment by shentonfreude** [comment]
On the 2D limitations, I find that I frequently use it for an overview, then slide the pane around so that I can zoom into a satellite after it's centered.  If I limited the pan, then the zoom wouldn't work so well -- you'd have to zoom first, losing sight of your target, then try to pan to find it. 

On +/- zoom buttons, this seems to go against what I've been reading in mobile-oriented design books: interaction with content vs interaction by navigation elements.  I do see the utility and notice that I've only recently gotten used to Google Maps' drag-to-zoom vs sliding the zoom slider. 

The view reset is an excellent idea.

Rotation of earth meaning the camera stays fixed in space and the earth rotates under it? I've considered doing this by fixing the eye to a satellite so you see what it would see. Would that be OK?  I have no idea how to implement yet but expect it's do-able.

**Comment by mikebrody** [comment]
Your 2D/2.5D argument makes sense. Maybe a long term solution is the ability for the user to fit the 2D view to their screen, but also allow them to go further out or in as they please. I feel like maximizing the horizontal space is particularly nice with a 2D view, visually.

I'm not wedded to +/- buttons, but I think some sort of UI element for zooming is necessary in a desktop environment. I like the idea of going mobile first, and if there was a way to detect the device and then hide certain UI elements on mobile to allow for only pinch-to-zoom I'd be open to that. However, it took me a minute to determine that two-finger swiping up and down gave me zoom effects on my trackpad. Using my mouse scroll wheel was a quicker association, but what's the current solution for a mouse user with only two buttons and no wheel?

Currently the user can spin the Earth as if it were a generic sphere, but I found it disorienting when I dragged the Earth around and it completely broke from it's "real" axis with no solution to return to a realistic orientation. A little more playing around shows that the rotation does stop to the point that the user can't completely flip the Earth upside-down, so that's good. Maybe a ghosted line running out of the top and bottom of the Earth at the poles?
